### ISSUE TITLE
Error on creation of sys restore point

### ISSUE THREAD

**Issue by lucas-timeworkstudio** [Raphire/Win11Debloat#231]
**Describe the bug**
Error in main script, ln 759. I did not go that deep into this so I don't have the actual issue yet but ill try to get it

**To Reproduce**
I do not have the steps, If you need them I can try to remember what options I picked on custom mode.

**Screenshots**

![Image](https://github.com/user-attachments/assets/6cb38d31-84be-4452-bd54-ac246e6f37e5)

**Additional context**
Fresh Install of Windows 11-Pro on VM Box.
Local User

**Comment by lucas-timeworkstudio** [comment]
To save whoever time the exact line is

**Checkpoint-Computer -Description "Restore point created by Win11Debloat" -RestorePointType "MODIFY_SETTINGS"**

and with context is

if ($recentRestorePoints.Count -eq 0) {
        **Checkpoint-Computer -Description "Restore point created by Win11Debloat" -RestorePointType "MODIFY_SETTINGS"**
        Write-Output "System restore point created successfully"
    }
    else {
        Write-Host "A recent restore point already exists, no new restore point was created." -ForegroundColor Yellow
    }

**Comment by lucas-timeworkstudio** [comment]
I believe this comes from how the VM Interacts with the script. However im going to keep this issue open until it gets resolved because I can't 100% say that its the VM

**Comment by Raphire** [comment]
It's possible that the system restore service is disabled on the VM. For now I have updated the script to handle an error when creating a restore point. [a888b9a](https://github.com/Raphire/Win11Debloat/commit/a888b9ae427e7e3bc6e516737e4b3f63f2db27e4)

**Comment by lucas-timeworkstudio** [comment]
> It's possible that the system restore service is disabled on the VM. For now I have updated the script to handle an error when creating a restore point.
> 
> Edit: [d294eb6](https://github.com/Raphire/Win11Debloat/commit/d294eb6b7a3ebff02e041e77c50e61fb856e3cd6)

Just retried with the new script and The same issue persists.

**Comment by lucas-timeworkstudio** [comment]
It's fine for now, but if anyone else needs vm testing this should be patched

**Comment by Raphire** [comment]
> > It's possible that the system restore service is disabled on the VM. For now I have updated the script to handle an error when creating a restore point.
> > Edit: [d294eb6](https://github.com/Raphire/Win11Debloat/commit/d294eb6b7a3ebff02e041e77c50e61fb856e3cd6)
> 
> Just retried with the new script and The same issue persists.

Yup, this was just a quick fix to prevent the script from acting like it succeeded with the restore. For the permanent solution the script will need to confirm the system restore service is actually enabled before proceeding.

**Comment by lucas-timeworkstudio** [comment]
I'll work on that

**Comment by Raphire** [comment]
This has been fixed with #235 ([09b4eb7](https://github.com/Raphire/Win11Debloat/commit/09b4eb7f6b65939ee9e243c16f2691860a009932))
