### ISSUE TITLE
Realtek Audio not regestering headphones

### ISSUE THREAD

**Issue by wolfieboy09** [Raphire/Win11Debloat#78]
**Describe the bug**
Before using, headphones that plug in the register, after running this, and restarting, it's not seeing my headphones.

**To Reproduce**
No idea

**Expected behavior**
For my headphones to register

**Screenshots**
The software has this from before
![image](https://github.com/Raphire/Win11Debloat/assets/105564186/7c111ff9-00cb-41d0-9bd1-a1a0b37c57dd)

**Comment by wolfieboy09** [comment]
![image](https://github.com/Raphire/Win11Debloat/assets/105564186/4be052b4-251a-4903-8fad-34ebe0dc4d56)
Reinstalled it and now its not even a thing

**Comment by wolfieboy09** [comment]
reinstalling from acer website now

**Comment by wolfieboy09** [comment]
UPDATE: I reinstalled from Acer's website, and its working!! It can register headphones and drivers are working!

**Comment by Raphire** [comment]
Heya,

Thanks for reporting this issue & keeping us updated with your solution. 

This is quite strange and I can't from the top of my head think of anything that might cause this. I'll see if I can find some time tomorrow to look into this issue further. Glad you managed to solve it though 🙃

**Comment by wolfieboy09** [comment]
I ran Win11Debloat with its default options, and one of the options (the one where a menu of checkmarks opens up I think) there might be a thing in there that has the registering part, and got uninstalled, causing RealTek not to find the headphones and see that they are plugged in. After some time (more then 5 mins of going around the internet), I downloaded the drivers fresh from Acer's website for my model I have, installed it, let it do its thing, and then it was working again.

**Comment by Raphire** [comment]
@wolfieboy09 Thanks for the additional info. 

I do see that Dolby is included in the list of apps that are removed. Do the acer audio drivers include Dolby?

**Comment by johnvo0918** [comment]
Suffering the same problem here but on a Lenovo Legion Slim 7 15ACH6. reinstalled realtek from lenovo's website, doesn't work.

**Comment by Raphire** [comment]
@johnvo0918 

Heya,

Sorry you ran into these issues. I'm glad you managed to fix it after some extensive troubleshooting. Thanks for reporting back with how you managed to get your audio setup working again.

I have preemptively removed Dolby from the apps that this script removes, it's the only thing that - logically - could/should have anything to do with audio related issues. 

@wolfieboy09 @johnvo0918 Could you check for me if you have any dolby apps installed now that you have fixed/reinstalled your audio driver packages?

**Comment by johnvo0918** [comment]
I did reinstall the Dolby app after and have not run the script since. After monitoring realtek has gone haywire again and crashed itself. Trying to look into what is actually causing this.

**Comment by Raphire** [comment]
@johnvo0918 were you able to fix/identify the issue?

**Comment by johnvo0918** [comment]
Nope, thankfully it has been behaving, bad for troubleshooting, great for me 😭

**Comment by Raphire** [comment]
> Nope, thankfully it has been behaving, bad for troubleshooting, great for me 😭

Thanks for getting back. I'm glad the issue seems to be fixed on your end :)

**Comment by Raphire** [comment]
Closing issue as the issue is fixed for both reporters & no new reports have been made since removing Dolby from appslist.

Feel free to open a new issue if this issue occurs in the future.

**Comment by johnvo0918** [comment]
What was the Dolby app that your script removes? The only dolby app I was able to find is Dolby Access https://apps.microsoft.com/detail/9n0866fs04w8 
Im trying to do everything that won't make me do a Windows reinstall, I got too much on my C-drive.

**Comment by johnvo0918** [comment]
New troubleshooting step because this problem persisted  so well that my parsec stopped getting audio from my other PC.

Safe mode -> Device Manager -> Uninstall Realtek

This is to prevent Windows to reinstall realtek immediately as soon as you uninstall realtek, windows does this during normal boot for some stupid reason.
After doing this, my audio is working okay now. Parsec started giving me audio from the host again. Will be monitoring closely.

**Comment by Raphire** [comment]
> What was the Dolby app that your script removes? The only dolby app I was able to find is Dolby Access https://apps.microsoft.com/detail/9n0866fs04w8 Im trying to do everything that won't make me do a Windows reinstall, I got too much on my C-drive.

Dolby Access seems to be the only listed dolby app now, but there's also [Dolby Vision](https://apps.microsoft.com/detail/9mvmz93n61t9?hl=en-us&gl=US) and possibly more. The script would've removed all MS Store apps from dolby. 

I'm still unsure why removing these apps would cause these driver issues though, as from my experience they're optional apps that can be uninstalled by the user normally without any impact.

I hope that uninstalling the drivers via safe mode has done the trick. Please do report back if you have any updates.

**Comment by johnvo0918** [comment]
yeah i went thru the code personally and cannot find anything in there that mentions Audio or anything related to audio drivers. Still scratching my head rn.

**Comment by johnvo0918** [comment]
Back again. It happened again. The audio device just freezes up and crashes. But it came back really fast this time.
The only event viewer thing I can find is this.

![image](https://github.com/user-attachments/assets/1806ca32-a3e2-4fd3-ae81-1fafab9cae15)

will be monitoring even closer.

**Comment by johnvo0918** [comment]
Look what I found. It happened again and I got the same error in event viewer.
![image](https://github.com/user-attachments/assets/ef8d5a5f-7039-4d1d-b291-0c0e6bae2e5b)

**Comment by Raphire** [comment]
Thanks for the update.

The svchost process contains many system processes, it's hard to pinpoint what exactly is causing it.

For reference, you can see all services that run inside the svchost process with this command: `Tasklist /SVC` 

I found some troubleshooting info here: https://techcommunity.microsoft.com/t5/ask-the-performance-team/getting-started-with-svchost-exe-troubleshooting/ba-p/372644

I think it might help to look at method 1 described in the article above to isolate certain processes (such as AudioSrv) to see if that service is the culprit, or that maybe something completely different is causing it.

**Comment by johnvo0918** [comment]
okay I mightve found something. The audio device crashing has something to do with the tweaks to the task bar because audio will work fine until I try to change my volume via the task bar. it starts to freeze the task bar, settings is no longer accessible BUT so far pressing on troubleshoot sound problems via right click makes windows reboot the audio services, which then bring audio devices back. No idea why this is happening, still monitoring closely.

**Comment by johnvo0918** [comment]
new error https://i.imgur.com/gR5f16Y.png
I do have oculus installed on this laptop Imma go ahead and disable it to see if I can repeat it.
But I have found a consistent way to force the laptop to crash my audio. literally just spam the volume slider LOL

**Comment by johnvo0918** [comment]
tried to run microsoft's recommended troubleshooter: 
https://i.imgur.com/FxkFE0A.png

**Comment by Raphire** [comment]
> tried to run microsoft's recommended troubleshooter: https://i.imgur.com/FxkFE0A.png

I think this may be related to uninstalled the Get Help app. Microsoft integrated many of the troubleshooters into this app. You can reinstall it here: https://apps.microsoft.com/detail/9pkdzbmv1h3t

**Comment by johnvo0918** [comment]
it's been awhile later. I'm still suffering from the issue I have no idea what is causing it. I'm this close to just completely reinstall windows. I can't get the app without the microsoft store btw 💀
thank god i don't daily drive the laptop anymore but this is a problem i will be closely monitoring until i can't take it anymore.
